@startuml class diagram
scale 1.8
class parametricPlotter
{
    -attributes
    +methods()
}
interface pEquation
object equation
package parameters <<rectangle>>
{
    struct t
    struct s
}
package dimension <<rectangle>> 
{
    struct X:dim_type
    struct Y:dim_type
}

parametricPlotter <--right-- pEquation : .     .
parametricPlotter <-- parameters
parametricPlotter <-- dimension
pEquation <|- equation


@enduml